name: Test Push Permissions

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  push-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}   # use a PAT with repo scope!

      - name: Configure Git for push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git"

      - name: Prepare or reuse branch
        run: |
          BRANCH="generated-template"
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/$BRANCH; then
            echo "Branch exists — checking it out."
            git checkout $BRANCH
            git pull origin $BRANCH
          else
            echo "Branch does not exist — creating it."
            git checkout -b $BRANCH
            git push -u origin $BRANCH
          fi

      - name: Append timestamp
        run: |
          echo "Updated at $(date -u)" >> push-test.txt
          git add push-test.txt
          git commit -m "test: append timestamp"
          git push origin generated-template

      - name: Show local and remote commits
        run: |
          echo "🧾 Local HEAD:"
          git log -1 --oneline
          echo
          echo "Fetching remote..."
          git fetch origin generated-template
          echo "🧾 Remote HEAD:"
          git log origin/generated-template -1 --oneline
